version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"     # Maps port 3000 on the host to the backend service
    volumes:
      - ./src/nest-app:/app   # Bind mounts the backend folder for live reloading (optional)
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:30"        # Maps port 8080 on the host to the frontend service (Nginx serving on port 80)
    volumes:
      - ./src/react-app:/app   # Bind mounts the frontend folder for live reloading (optional)
    environment:
      - NODE_ENV=production
