FROM node:16-alpine

WORKDIR /app

COPY hepsi_frontend/package*.json ./

RUN npm install

RUN npm list react-scripts

COPY hepsi_frontend/ ./

RUN npm install -g nodemon

EXPOSE 8000

CMD ["npm", "start"]
