FROM node:16-alpine AS build

WORKDIR /app

COPY hepsi_frontend/package*.json ./

RUN npm install

COPY hepsi_frontend/ .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 3001

CMD ["nginx", "-g", "daemon off;"]
