FROM node:16-alpine

WORKDIR /app

# Copy the package.json and package-lock.json specifically from the hepsi_frontend folder
COPY hepsi_frontend/package*.json ./

RUN npm install

RUN npm list react-scripts

COPY hepsi_frontend/ ./

RUN npm install -g nodemon

EXPOSE 8000

CMD ["npm", "start"]
