version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src              
      - /app/node_modules             
    ports:
      - "3000:3000"
    env_file:
      - .env  
    depends_on:
      - db
      - redis
    networks:
      - hepsi_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./hepsi_frontend:/app           
      - /app/node_modules              
    ports:
      - "8000:8000"
    depends_on:
      - backend
    networks:
      - hepsi_network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}  
      MYSQL_DATABASE: ${DB_NAME}           
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - hepsi_network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hepsi_network

volumes:
  db_data:
  redis_data:

networks:
  hepsi_network:
    driver: bridge
